"""init

Revision ID: cd4d86acd11f
Revises: 
Create Date: 2023-09-15 23:44:19.179177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cd4d86acd11f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("telegram_id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("telegram_id"),
    )
    op.create_table(
        "chats",
        sa.Column("telegram_id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.telegram_id"]),
        sa.PrimaryKeyConstraint("telegram_id"),
    )
    op.create_table(
        "users_dialog",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(), nullable=True),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.telegram_id"]),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "users_settings",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("language", sa.Enum("RUSSIAN", "ENGLISH", name="languageenum"), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.telegram_id"], ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "chats_users",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.Enum("MANAGER", "MEMBER", name="roleenum"), nullable=False),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.telegram_id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.telegram_id"]),
        sa.PrimaryKeyConstraint("user_id", "chat_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chats_users")
    op.drop_table("users_settings")
    op.drop_table("users_dialog")
    op.drop_table("chats")
    op.drop_table("users")
    # ### end Alembic commands ###
